OBJS = ast.cmo sast.cmo parser.cmo scanner.cmo symbolTable.cmo semantic_check.cmo summa.cmo

summa : $(OBJS)
	ocamlc -o summa -g unix.cma $(OBJS)

.PHONY : test
test : summa testall.sh
	./testall.sh

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c -g $<

%.cmi : %.mli
	ocamlc -c -g $<

.PHONY : clean
clean :
	rm -rf summa parser.ml parser.mli scanner.ml \
	*.cmo *.cmi *.out *.diff *~  a.out.dSYM

# Generated by ocamldep *.ml *.mli
ast.cmo:
ast.cmx:
sast.cmo: ast.cmo
sast.cmx: ast.cmx
symbolTable.cmo: ast.cmo sast.cmo
symbolTable.cmx: ast.cmx sast.cmx
semantic_check.cmo: symbolTable.cmo
semantic_check.cmx: symbolTable.cmx
parser.cmo: ast.cmo parser.cmi
parser.cmx: ast.cmx parser.cmi
scanner.cmo: parser.cmi
scanner.cmx: parser.cmx
parser.cmi: ast.cmo
summa.cmo: scanner.cmo parser.cmi ast.cmo symbolTable.cmo semantic_check.cmo
summa.cmx: scanner.cmx parser.cmx ast.cmx symbolTable.cmx semantic_check.cmx