OBJS = ast.cmo parser.cmo scanner.cmo semantic_check.cmo summa.cmo

summa : $(OBJS)
	ocamlc -o summa -g unix.cma $(OBJS)

.PHONY : test
test : summa testall.sh
	./testall.sh

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c -g $<

%.cmi : %.mli
	ocamlc -c -g $<

.PHONY : clean
clean :
	rm -rf summa parser.ml parser.mli scanner.ml \
	*.cmo *.cmi *.out *.diff *~  a.out.dSYM test_all.log

new : clean summa

# Generated by ocamldep *.ml *.mli
ast.cmo:
ast.cmx:
parser.cmo: ast.cmo parser.cmi
parser.cmx: ast.cmx parser.cmi
parser.cmi: ast.cmo
scanner.cmo: parser.cmi
scanner.cmx: parser.cmx
semantic_check.cmx: semantic_check.cmx
semantic_check.cmi: semantic_check.cmo
summa.cmo: scanner.cmo parser.cmi ast.cmo
summa.cmx: scanner.cmx parser.cmx ast.cmx